openapi: 3.0.0
x-stoplight:
  id: umm0in1sr7ncy
info:
  title: sample-api
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content: {}
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
  /users:
    get:
      summary: ''
      operationId: get-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    parameters: []
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                phoneNumber:
                  type: string
                dob:
                  type: string
                  format: date-time
                gender:
                  type: string
                password:
                  type: string
  /auth/login:
    post:
      summary: Login
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                  accessToken:
                    type: string
        '400':
          description: User Not Found
        '404':
          description: Not Found
      operationId: post-auth-login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                "\_account":
                  type: string
                password:
                  type: string
  /auth/register:
    post:
      summary: Register
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                    format: email
                  accessToken:
                    type: string
        '400':
          description: Bad Request
      operationId: post-auth-register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                phoneNumber:
                  type: string
                dob:
                  type: string
                  format: date-time
                gender:
                  type: string
                password:
                  type: string
components:
  schemas:
    User:
      title: User
      type: object
      x-examples:
        Example 1:
          id: 0
          username: string
          email: user@example.com
          phoneNumber: string
          dob: '2019-08-24T14:15:22Z'
          gender: string
          createdAt: '2019-08-24T14:15:22Z'
          updatedAt: '2019-08-24T14:15:22Z'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        username:
          type: string
        email:
          type: string
          format: email
        phoneNumber:
          type: string
        dob:
          type: string
          example: '2019-08-24T14:15:22Z'
          format: date-time
        gender:
          type: string
          description: Set to true if the user's email has been verified.
        createdAt:
          type: string
          description: The date that the user was created.
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - email
        - phoneNumber
    Post:
      title: Post
      x-stoplight:
        id: m30zg8wlmy411
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      x-examples:
        Example 1:
          id: 0
          title: This is my title
          body: This is my content
          createdAt: '2019-08-24T14:15:22Z'
          updatedAt: '2019-08-24T14:15:22Z'
